name: Dev Assistant Discord Bot deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source env/bin/activate
        python -m unittest

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy Discord Bot
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -v -p 2222 -o StrictHostKeyChecking=no devassistant@srv260.prodns.com.br "cd /home2/devassistant/DevAssistantDiscordBot/ && git fetch && git reset --hard origin/main && source env/bin/activate && pip install -r requirements.txt"